name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: my-container-image
  OWNER: safaie
  TAG: $(date +%s)
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: Log in to the Container registry
        run: docker login ${{ env.REGISTRY }} -u ${{ env.OWNER }} -p ${{ secrets.GITHUB_TOKEN }}
       
      - name: Build and tag the Docker image
        run: docker build . --file ./sample-packages/docker/Dockerfile --tag ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        
      - name: Push the Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

        
